### PR TITLE
Added plugin for CRYSTAL code, developed in Turin University

### PR DESCRIPTION
**Pull request by blokhin**
By @ansobolev

### CODE REVIEW

**Comment by ltalirz** [comment]
Thanks for this addition @blokhin !

Since there already is a rather well developed plugin for crystal17 by @chrisjsewell
https://aiidateam.github.io/aiida-registry/plugins/crystal17.html
could I ask how your plugin differs from this one?

Would there perhaps be a potential for joining resources and working together?

**Comment by ltalirz** [comment]
One minor point: travis indicates there seems to be an issue with installing your plugin from the repo:

https://travis-ci.org/aiidateam/aiida-registry/jobs/597856729#L371
```
Cannot unpack file /tmp/pip-unpack-gzni45cm/aiida-crystal (downloaded from /tmp/pip-req-build-0ewt1iad, content-type: text/html; charset=utf-8); cannot detect archive format\nCannot determine archive format of /tmp/pip-req-build-0ewt1iad\n'
```
Do you happen to have an idea where this might come from?

**Comment by chrisjsewell** [comment]
Yes well, here's where it gets interesting. As it says on there README, it is actually just a copy of my code in January (commit 5855d74a41fdcea7748d0fa93a582c38f2f55a37), but adapted to use a different raw parser for the `stdout` output file, and then they have made a few changes to make it compatible with `aiida v1`.

Since then I've basically rewritten my whole code base to work better with `aiida v1` and improve documentation, adding numerous more calculations and workflows (as detailed in my [changelog](https://aiida-crystal17.readthedocs.io/en/develop/changelog.html)). For example, their [main calculation class](https://github.com/tilde-lab/aiida-crystal/blob/8317393de32f4933c129506d95fded665f13fb23/aiida_crystal/calculations/common.py#L17) contains only one exit codes, whereas [mine](https://github.com/chrisjsewell/aiida-crystal17/blob/bd56476e8a06359f730b083cc28964782d7f1270/aiida_crystal17/calculations/cry_abstract.py#L25) contains about 20, which I then use in my `RestartWorchain` (similar to the one in aiida-quantumespresso).

I'd be happy to collaborate, but I'm a bit disappointed that @blokhin did not contact me about this previously.

**Comment by blokhin** [comment]
Dear @chrisjsewell,

we decided to use your code in 01/2019 by many reasons: decent design and architecture, high quality, and very permissive [MIT license](https://github.com/chrisjsewell/aiida-crystal17/blob/5855d74a41fdcea7748d0fa93a582c38f2f55a37/LICENSE) — which we do respect. There were also the things we were unsure (parser and heavy dependencies), so we changed them. We also rewrote and adopted your code to the completely different aims and project (`high-throughput cloud calculations based on the MPDS`). In those conditions an efficient collaboration would be hard, so we went on our own and diverged. We hope for your understanding!

**Comment by blokhin** [comment]
@ltalirz @chrisjsewell I agree, in future it's better to have one multi-purpose plugin, instead of specific two. Let me try to estimate the needed efforts for that. However for now, I believe, both our works deserve mentioning in this registry.

@ltalirz `pip_url` fixed.

**Comment by chrisjsewell** [comment]
> We also rewrote and adopted your code to the completely different aims

I'm sorry but I disagree with this statement. There is very little that has been rewritten in the core code, and I see only limited use cases where `aiida-crystal17` could not be used; really the only addition you have made is to parse phonon and elastic data from the `stdout` (see [here](https://github.com/tilde-lab/aiida-crystal/blob/8317393de32f4933c129506d95fded665f13fb23/aiida_crystal/io/pycrystal/out.py#L47)), which could easily be added to `aiida-crystal17`.

Moreover, `aiida-crystal` is completely undocumented, and has very minimal testing.

> heavy dependencies

I have actually already moved the raw parsers from `ejplugins` (that you mention [here](https://github.com/tilde-lab/pycrystal#related-work) into `aiida-crystal17` and removed these dependencies, and made many other improvements.

> permissive MIT license — which we do respect

Yes this is quite true (although now it is actually LGPL), and I'm absolutely happy for my work to be utilised. But I hope you can see where I take issue with you now implying that this should be a separate entity in the registry.

**Comment by ltalirz** [comment]
@blokhin @chrisjsewell 
Let me first of all say that, from my point view, we are always happy when people who put work into their AiiDA plugins make their work publicly available and register them here.
I now understand that @blokhin et al. were aware of the crystal17 plugin when they started development, and so for me the plugin registry served its purpose.

While I would usually suggest to contact the developer of an existing plugin, I understand that there can sometimes be requirements (time, use case, ...) that prohibit one from doing this and force one to start hacking away on your own. I think this is fine.

When registering the new plugin on the AiiDA registry, I think it would be helpful to provide some guidance to new users - as a Crystal user I would now wonder: which plugin should I use?
Also, the name `aiida-crystal` being more general than `aiida-crystal17` suggests that the plugin is more general (is it?).

Do you have a suggestion for an alternative name that would convey the particular purpose of the plugin? (something like `aiida-crystal-mpds`, perhaps a bit shorter?)

**Comment by ltalirz** [comment]
Besides the name, which we should discuss, there is also the description that could be updated to help users understand when they should use this plugin
```
"description": "Yet another AiiDA plugin for CRYSTAL code",
```

**Comment by blokhin** [comment]
Allright, colleagues, let me think.

**Comment by ltalirz** [comment]
@blokhin just a reminder that we're happy to add the plugin under a name (& description) that provides a bit of context about its intended usage

**Comment by blokhin** [comment]
@ltalirz changed, as you suggested. Much appreciated!

**Comment by ltalirz** [comment]
Thanks @blokhin for updating the name & description in the `plugins.json`!  I notice that you kept the name of the pypi package, the name of the package in the repo and the entry point prefix the unchanged (aiida-crystal / aiida_crystal / crystal). 

Basically all other plugins on the registry follow the convention that the registered name and the name of the package are the same, and having differences here might confuse users.
Would you be willing to update this to aiida-crystal-mpds as well?

**Comment by blokhin** [comment]
In principle I‘m ready to do that, if you suggest. However that will be a bit painful for our own internal dependencies resolution, so I‘d ask for some deferral.

**Comment by blokhin** [comment]
@ltalirz alright, updated as you suggested. Please, review.

**Comment by ltalirz** [comment]
Thanks for the update @blokhin , much appreciated!

As mentioned above, would it be possible to update the entry point prefix to `crystal_dft` as well?
Cheers,
Leo

**Comment by blokhin** [comment]
No problem!

**Comment by ltalirz** [comment]
Thanks @blokhin , I'm going to merge this now.

Please make sure to also follow the entry point prefix specified here, i.e. use it here:
https://raw.githubusercontent.com/tilde-lab/aiida-crystal-dft/master/setup.json

**Pull request merged**
