### PR TITLE
Add PR preview action

### PR DESCRIPTION
**Pull request by AhmedBasem20**
This will create a PR preview link for the website when #240 is merged.

### CODE REVIEW

**Comment by AhmedBasem20** [comment]
@unkcpz

**Comment by unkcpz** [comment]
Thanks! Seems the json file is not there. I remember you discuss this with @ltalirz in the first meeting, you know how to fix it? Pin me again when it is ready to review.

**Comment by AhmedBasem20** [comment]
Hi @unkcpz, I tried this for the current website but it seems that there is a permission issue,
from the README of [`pr-preview-action`](https://github.com/rossjrw/pr-preview-action), I found out that this Action does not currently support deploying previews for PRs from forks. Is there any alternative/solution to look for?


> Seems the json file is not there.

I think It was because the `aiida-registry-app` directory that contains the react app is not there

**Comment by unkcpz** [comment]
>  I found out that this Action does not currently support deploying previews for PRs from forks. Is there any alternative/solution to look for?

I give you the write permission to the repository, since you are working on this, it is fair to give you this permission. You can push to the repo and manage issues.

**Comment by AhmedBasem20** [comment]
Thanks! will close this and open a new one.

**Pull request closed without merging**
