### PR TITLE
Add aiida-sssp-workflow plugin

### PR DESCRIPTION
**Pull request by unkcpz**

### CODE REVIEW

**Comment by ltalirz** [comment]
@AhmedBasem20 , the new section in action - very nice

image

**Comment by unkcpz** [comment]
Yes, very nice! But since the container uses `aiida-core==2.3.1` and my plugin requires `aiida-core~=2.4.0` so it tries to install the old version of my plugin. 😂

**Comment by ltalirz** [comment]
Why is the container not up to date?

**Comment by unkcpz** [comment]
Two issues. First the `aiida-core` was not yet released after the new docker stack was built, so the tag that can be used is `aiida-core-with-services:edge`, the edge is from the main branch. It is better to use `latest` tag which points to the latest released version. Second, the time needed to run a test install is more than 2 times longer. Since the new docker stack will force us to wait for the services to start.

**Comment by unkcpz** [comment]
Just did a close look at why it takes so long for the new docker stack, the time to start the container is not too much but with the new version of aiida-core where python 3.8 was deprecated, lots of plugins just can not installed and takes very long to search for correct dependencies. Thus I think it makes sense to accept the test install time is long and I increase the CI timeout to 180 in #280. Let's go and discuss it there.

**Comment by ltalirz** [comment]
> with the new version of aiida-core where python 3.8 was deprecated, lots of plugins just can not installed and takes very long to search for correct dependencies.

this is rather worrying to me... does this indicate it would be a good idea to delay this deprecation?

**Comment by unkcpz** [comment]
> does this indicate it would be a good idea to delay this deprecation?

But this is already happened. I thought it won't be a problem but now I realize that if people check the aiida-registry page, it will give a false impression that a plugin cannot be used which does not support py3.9 yet but all fine in python3.8+aiida-core<2.4.0. 

I'll compare and see how many plugins encounter such problems and see if we need to worry about it in here or `aiida-core` or just tell some plugins to migrate to python3.9 (if only 2 or 3 I think this is the easiest way to do so).

**Comment by unkcpz** [comment]
I realize another catch in terms of docker stack. The install test can actually override the `aiida-core`, which is why some plugins which not migrated to aiida 2.x still can pass the install test. I think this is not proper. Instead, I'd propose to be more aggressively pinning the `aiida-core` version as a strict dependency inside the docker image this will prevent plugins that are not compatible with `aiida-core` version of the container from falsely passing the test.

**Comment by ltalirz** [comment]
> But this is already happened. I thought it won't be a problem but now I realize that if people check the aiida-registry page, it will give a false impression that a plugin cannot be used which does not support py3.9 yet but all fine in python3.8+aiida-core<2.4.0.
> 
> I'll compare and see how many plugins encounter such problems and see if we need to worry about it in here or `aiida-core` or just tell some plugins to migrate to python3.9 (if only 2 or 3 I think this is the easiest way to do so).

I suspect that most plugins will work fine with Python 3.9, but some may have outdated requirements.
If that is the case, we may want to wait with the upgrade


>  I realize another catch in terms of docker stack. The install test can actually override the aiida-core, which is why some plugins which not migrated to aiida 2.x still can pass the install test. I think this is not proper. Instead, I'd propose to be more aggressively pinning the aiida-core version as a strict dependency inside the docker image this will prevent plugins that are not compatible with aiida-core version of the container from falsely passing the test.

That is correct and I agree the aiida-core version should be pinned.

**Comment by unkcpz** [comment]
Superseded by https://github.com/aiidateam/aiida-registry/pull/299

**Pull request closed without merging**
