### PR TITLE
aiida-mlip plugin

### PR DESCRIPTION
**Pull request by federicazanca**
aiida-mlip plugin 
machine learning interatomic potentials aiida plugin

### CODE REVIEW

**Comment by ltalirz** [comment]
Hey @federicazanca , thanks for adding aiida-mlip to the registry!

I noticed in the docs preview a few suggestions, could you have a look? https://aiidateam.github.io/aiida-registry/pr-preview/pr-304/
image

**Comment by ltalirz** [comment]
hey @unkcpz , when you have time, would you be able to have a look at why this is failing?
it seems like there is an authentication problem (seems unrelated to this pull request)

**Comment by unkcpz** [comment]
Sure! I'll check it.

**Comment by unkcpz** [comment]
Hi @federicazanca, I disable the preview action in dev-CI, the failed one is duplicate as the the preview from plugin-CI and only should be run for PR from `aiidateam/aiida-registry`. Can you update the PR (I guess you can see the "Update Branch" button? I cannot since the PR is from your repo, I assume.) Then all tests should pass.

**Review by unkcpz — CHANGES_REQUESTED** [review]
Thanks @federicazanca! 
Although all tests passed, the installation test is not running since you didn't specify the `pip_url` and the development status classifier is set to "alpha" (https://github.com/stfc/aiida-mlip/blob/18695f7793d99b5dd632bfa8d4a60057ffc64930/pyproject.toml#L18C6-L18C24)

I notice you already had the package published on pypi so I proposed the change to test installation, if everything goes fine you can see the plugin port details in the detail page. 

Please also not to update the development status in the `pyproject.toml` file of `aiida-mlip` to beta or higher once you think it is proper.

**Review by unkcpz — APPROVED** [review]
Thanks! @federicazanca

**Comment by federicazanca** [comment]
thank you and I'll keep it updated, still working on some main features

**Pull request merged**
