### PR TITLE
Update plugins.yaml with aiida-fans

### PR DESCRIPTION
**Pull request by ethan-shanahan**
Added the `aiida-fans` plugin specification to the `plugins.yaml` file.

### CODE REVIEW

**Comment by ethan-shanahan** [comment]
Thanks for looking into this. I've updated the README.

**Review by unkcpz — COMMENTED** [review]
Thanks @ethan-shanahan for adding the README. It seems the link of the FANS repository is broken?

**Comment by ethan-shanahan** [comment]
Yeah sorry about that @unkcpz. The links should be fixed now.

**Review by unkcpz — APPROVED** [review]
Thanks for the fix.

**Pull request merged**
