### PR TITLE
add comment with plugin issues

### PR DESCRIPTION
**Pull request by ltalirz**

### CODE REVIEW

**Comment by ltalirz** [comment]
@csadorf I've been following your approach from the aiida-core repo here to add a comment in the PR.

While the `commit-comment` action evidently works, for some reason the corresponding github action fails with
```
Error: Resource not accessible by integration
```
Do you happen to have an idea why that might be?

**Comment by csadorf** [comment]
> @csadorf I've been following your approach from the aiida-core repo here to add a comment in the PR.
> 
> While the `commit-comment` action evidently works, for some reason the corresponding github action [fails](https://github.com/aiidateam/aiida-registry/pull/169/checks?check_run_id=2511986791#step:7:58) with
> 
> ```
> Error: Resource not accessible by integration
> ```
> 
> Do you happen to have an idea why that might be?

Looks like you might need to provide the `GITHUB_TOKEN` secret: https://github.com/aiidateam/aiida-core/blob/f3c335965b301af97b2d91e50b67ae57d3c5cacc/.github/workflows/test-install.yml#L223

Which makes me wonder whether [this step](https://github.com/aiidateam/aiida-core/blob/2bb18e015c32cdb23e6aab2476e9b9a217194aa3/.github/workflows/ci-code.yml#L32-L40) might be actually broken. 😕

**Comment by ltalirz** [comment]
Thanks @csadorf for the hint, it seems that doesn't solve the issue though...
I'm really a bit puzzled here - but I take it that you've never seen this?

**Comment by ltalirz** [comment]
Oh, now I see that there is another difference: your check runs only on pull request, while this one runs both on push and pull request. I'll check whether that makes the difference

**Comment by csadorf** [comment]
> Thanks @csadorf for the hint, it seems that doesn't solve the issue though...
> I'm really a bit puzzled here - but I take it that you've never seen this?

No, I do not recall seeing that particular error.

> Oh, now I see that there is another difference: your check runs only on pull request, while this one runs both on push and pull request. I'll check whether that makes the difference

That might well be the case. The issue becomes even more complicated for PRs from forks.

**Pull request merged**
