### PR TITLE
fix: don't choke on missing pip url

### PR DESCRIPTION
**Pull request by ltalirz**
Web site build broke because one package did not specify pip_url

### CODE REVIEW

**Comment by ltalirz** [comment]
@unkcpz do you have an idea why the checks aren't running?

also tried pushing to the upstream repo, but even there the checks are not running https://github.com/aiidateam/aiida-registry/commits/fix/missing-pip-url/

this commit does not touch the github actions files, so I don't quite get what's going on here

**Comment by unkcpz** [comment]
> Web site build broke because one package did not specify pip_url

I didn't understand why it was not failed before, the error is from aiida-open_circuit_voltage

For the CI not triggered, it will be fixed by #307.

**Comment by unkcpz** [comment]
Sorry, accidentally close it through #307

**Review by unkcpz — APPROVED** [review]
The changes looks all good, although as I mentioned in the previous comment, I don't know why it was only failed recently. I approve it to not block the page build.

**Comment by ltalirz** [comment]
Thanks a lot @unkcpz !

**Pull request merged**
