### PR TITLE
don't run cronjob on forks

### LINKED ISSUE #164: Add guards to avoid running GH actions on forks
Example: https://github.com/aiidateam/aiida-quantumespresso/blob/1ad9842942312879c31555693646e8475eaec455/.github/workflows/develop.yml#L11

### PR DESCRIPTION
**Pull request by ltalirz**
close #164

### CODE REVIEW

**Comment by ltalirz** [comment]
thanks @greschd!

**Comment by greschd** [comment]
thank you, one less e-mail landing in my spam folder ;)

**Comment by ltalirz** [comment]
well, now everyone will need to update their master branch... perhaps I should put a message in the plugin-developers thread?

**Comment by greschd** [comment]
Yeah, I guess that'd make sense.

**Pull request merged**
