### PR TITLE
Add aiida-aimall to plugins.yaml

### PR DESCRIPTION
**Pull request by kmlefran**
Register aiida-aimall

### CODE REVIEW

**Comment by ltalirz** [comment]
hey @kmlefran , thanks for registering your plugin on the AiiDA plugin registry!

I notice a warning about the python version in the docs built from the pull request https://aiidateam.github.io/aiida-registry/pr-preview/pr-300/aiida-aimall

Can you comment on where that comes from / whether it is indeed a problem?

**Comment by kmlefran** [comment]
I tried adjusting some stuff in my packages pyproject.toml but seems like the same issue on the new preview. I'm not sure why that would be, on my end I have no issues installing. Maybe could be due to h5 headers in the aiida-dataframe tables dependency? But I don't understand why there is an error with the Python version in the preview. Sorry but I'm relatively new to developing packages.

On my end, I was able to install my package no problem in a conda environment with `pip install --pre` as the error message suggests the registry is having issues with.

```python
conda create -n install_test
conda activate install_test
conda install h5py # h5 headers
pip install --pre aiida-aimall
```

**Comment by ltalirz** [comment]
Hey @kmlefran , thanks for looking into this.

This is interesting, and I guess it suggest some issue on the side of the test done by the aiida registry. I will open an issue for this.

In the meanwhile, happy to merge your PR as you confirm installation works fine.

**Review by ltalirz — APPROVED** [review]

**Comment by unkcpz** [comment]
The reason is that docker image used to test build is based on our official `aiida-core-with-services` image which [pinned the python version to `3.10`](https://github.com/aiidateam/aiida-core/blob/6dd8ecaabf95f954d329e9e19095290f4110a564/.docker/build.json#L4). Since in your package the minimal python version is pinned to 3.11, the check is fail. 

To exactly reproduce how the checks are running, you can use `aiida-core-with-services` by docker, as documented in https://aiida.readthedocs.io/projects/aiida-core/en/latest/intro/run_docker.html. You'll get an identical environment as checks are running.

**Comment by unkcpz** [comment]
Hi @kmlefran, can you try to loose on the python version to include py3.10 and make a release? Or there are py3.10 features you used in the plugin?

**Comment by kmlefran** [comment]
Hi, sorry for the delay, just had a new baby so been busy. I've enabled Python 3.10 and created a new release.

**Comment by unkcpz** [comment]
Thanks @kmlefran and congratulation! 

Once #314 is merged, the entrypoints will shown, the error is from an issue from aiida-registry side.
The plugin details are now all shown, please take a look at the preview https://aiidateam.github.io/aiida-registry/pr-preview/pr-314

**Comment by unkcpz** [comment]
@kmlefran all fixed! ;) https://aiidateam.github.io/aiida-registry/aiida-aimall

**Comment by kmlefran** [comment]
Great, thanks! Also, unrelated to this PR but updated my defaults to best practice now after reviewing #314

**Pull request merged**
