### PR TITLE
plugins: add aiida-graphql

### PR DESCRIPTION
**Pull request by dev-zero**
will likely also send a patch for the generator to parse `pyproject.toml` instead of the `setup.json`

### CODE REVIEW

**Comment by ltalirz** [comment]
That is really cool!
We were actually discussing about a graphQL alternative to the REST API in Moscow two days ago.

Concerning the setup.json vs pyproject.toml: Your plugin would now be the first to break with this tradition. Is it worth breaking? And is the pyproject.toml a full replacement?

This is an honest question, and if you can convince @giovannipizzi and @sphuber as well, we might switch.

**Comment by dev-zero** [comment]
> That is really cool!
> We were actually discussing about a graphQL alternative to the REST API in Moscow two days ago.

Nice :) last time I talked to @giovannipizzi it wasn't really a topic yet if I remember correctly.

> Concerning the setup.json vs pyproject.toml: Your plugin would now be the first to break with this tradition. Is it worth breaking? And is the pyproject.toml a full replacement?

For the majority of the packages I'd say it will be worth to switch (less files to manage since they likely will have to add a minimal `pyproject.toml` anyway), but there are a couple of things to know:

The only thing which is standardized by [PEP 518](https://www.python.org/dev/peps/pep-0518/) in the `pyproject.toml` is the `[build-system]` section. Everything else is as specific to the used build system as is most of a modern `setup.py/setup.json` to `setuptools.`
From what I gathered there are currently two alternative build systems using `pyproject.toml` fully: [Poetry](https://poetry.eustace.io/) and [Flit](https://flit.readthedocs.io/).

So, besides the switch to `pyproject.toml` the question is rather: which build system should we recommend, if any?

Both of the build systems should support setuptools-style entry point groups, optional package dependency groups, etc. Meaning that you should be able to fully replace a `setup.json/py` with one of them. But they need separate parsing (at least for the section name):

```
[tool.poetry.plugins."blogtool.parsers"]
".rst" = "some_module:SomeClass"
```
vs.
```
[tool.flit.entrypoints."blogtool.parsers"]
".rst" = "some_module:SomeClass"
```

Note: as soon as the packages are released on PyPI as Wheels the build system used to prepare them does not matter anymore.

I think the `aiida-graphql` project would a good point for a trial (since it is not a plugin like the others, except maybe for a toplevel verdi command - but for this there's no entry point group yet) but I would not recommend to switch over from setuptools completely just yet, especially not since the `reentry` package has a hard dependency on `setuptools` to resolve the entry points.

**Comment by dev-zero** [comment]
> will likely also send a patch for the generator to parse `pyproject.toml` instead of the `setup.json`

hmm, this I have to pospone a bit since it is more involved: Poetry allows for more elaborate version specifiers: https://poetry.eustace.io/docs/versions/

**Comment by ltalirz** [comment]
> hmm, this I have to pospone a bit since it is more involved: Poetry allows for more elaborate version specifiers: https://poetry.eustace.io/docs/versions/

Ok, do I understand correctly that I should still wait with this PR?

I also notice that pip install using the provided pip_url (here: package name) fails:
https://travis-ci.org/aiidateam/aiida-registry/jobs/599250898#L406

**Comment by dev-zero** [comment]
> > hmm, this I have to pospone a bit since it is more involved: Poetry allows for more elaborate version specifiers: https://poetry.eustace.io/docs/versions/
> 
> Ok, do I understand correctly that I should still wait with this PR?

Not necessarily. It seems that the scripts can handle a missing `setup.json` for now, so it could be merged.

> I also notice that pip install using the provided pip_url (here: package name) fails:
> https://travis-ci.org/aiidateam/aiida-registry/jobs/599250898#L406

Yes, there's no release yet. But I will do one today, safer anyway.

**Comment by dev-zero** [comment]
I opened issue #92 as feature request for supporting alternative build systems

**Comment by dev-zero** [comment]
> > I also notice that pip install using the provided pip_url (here: package name) fails:
> > https://travis-ci.org/aiidateam/aiida-registry/jobs/599250898#L406
> 
> <s>Yes, there's no release yet. But I will do one today, safer anyway.</s> There is one now

Although it will likely fail since it requires Python 3.7 (for the Strawberry-GraphQL library)

**Comment by ltalirz** [comment]
> Although it will likely fail since it requires Python 3.7 (for the Strawberry-GraphQL library)

Ok, feel free to change the python3 version of the travis test to python3.7

**Pull request merged**
