### PR TITLE
add aiida-icon plugin to the list

### PR DESCRIPTION
**Pull request by DropD**
Adding `aiida-icon`, the (first?) plugin for the weather and climate field. It's being developed at CSCS primarily for C2SM and EXCLAIM, in close cooperation with AiiDA-Team.

### CODE REVIEW

**Comment by unkcpz** [comment]
Thanks @DropD!
If you go to https://aiidateam.github.io/aiida-registry/pr-preview/pr-338/, it has a dependencies error. I think the reason is you restrict python version to >= 3.12, but the package build and test is run on python 3.10 (in order to make sure that the plugin can be used for all aiida-core supported python version).

**Comment by DropD** [comment]
> Thanks @DropD! If you go to https://aiidateam.github.io/aiida-registry/pr-preview/pr-338/, it has a dependencies error. I think the reason is you restrict python version to >= 3.12, but the package build and test is run on python 3.10 (in order to make sure that the plugin can be used for all aiida-core supported python version).

It looks like that's an easy fix and I'm working on it.

**Comment by unkcpz** [comment]
Ah, I actually bump the python version to 3.10 used in docker image. https://github.com/aiidateam/aiida-core/blob/main/.docker/build.json

**Comment by DropD** [comment]
Officially supporting and testing 3.10 - 3.13 now 👍

**Review by unkcpz — APPROVED** [review]
Cool, all checks passed! Thanks @DropD

**Pull request merged**
